### ISSUE TITLE
还有后续更新计划吗？

### ISSUE THREAD

**Issue by haohaoalt** [KennyWGH/LIV-SLAM#1]

**Comment by KennyWGH** [comment]
工作后事情比较多，后续会维护单独的视觉vins工程和若干激光项目，这个项目不再更新了，感谢关注


Kenny

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年3月13日 16:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | Re: [KennyWGH/LIV-SLAM] 还有后续更新计划吗？ (Issue #1) |

Closed #1 as completed.
